-- =============================================
-- INSOLIT - Seed Data IDF (moderate volume)
-- Run this AFTER schema.sql and seed.sql
-- Scope: Paris 75 only
-- =============================================

BEGIN;

-- Enforce Paris-only scope in current data
DELETE FROM promos p
USING merchants m
WHERE p.merchant_id = m.id
  AND m.address !~ ' 75[0-9]{3} ';

DELETE FROM merchants
WHERE address !~ ' 75[0-9]{3} ';

-- Clean only rows generated by this file (safe rerun)
DELETE FROM promos
WHERE promo_code LIKE 'IDF-%';

DELETE FROM merchants
WHERE name LIKE 'IDF %';

-- -------------------------------------------------
-- 1) Additional merchants in Paris
-- -------------------------------------------------
WITH idf_cities AS (
  SELECT *
  FROM (
    VALUES
      ('Paris', '75001', 48.8625, 2.3361, 9),
      ('Paris', '75002', 48.8686, 2.3449, 9),
      ('Paris', '75003', 48.8635, 2.3600, 8),
      ('Paris', '75004', 48.8548, 2.3570, 8),
      ('Paris', '75005', 48.8448, 2.3470, 8),
      ('Paris', '75006', 48.8510, 2.3324, 8),
      ('Paris', '75007', 48.8565, 2.3211, 7),
      ('Paris', '75008', 48.8722, 2.3126, 7),
      ('Paris', '75009', 48.8760, 2.3370, 6),
      ('Paris', '75010', 48.8761, 2.3590, 6),
      ('Paris', '75011', 48.8566, 2.3522, 6),
      ('Paris', '75012', 48.8402, 2.3878, 5),
      ('Paris', '75013', 48.8323, 2.3562, 5),
      ('Paris', '75014', 48.8331, 2.3264, 5),
      ('Paris', '75015', 48.8414, 2.3006, 5),
      ('Paris', '75016', 48.8630, 2.2769, 4),
      ('Paris', '75017', 48.8840, 2.3210, 5),
      ('Paris', '75018', 48.8924, 2.3444, 5),
      ('Paris', '75019', 48.8870, 2.3840, 4),
      ('Paris', '75020', 48.8648, 2.3987, 4)
  ) AS t(city, postal_code, lat, lng, weight)
), categories_ranked AS (
  SELECT
    c.id,
    c.label,
    row_number() OVER (ORDER BY c.id) AS rn,
    COUNT(*) OVER () AS total
  FROM categories c
), merchant_rows AS (
  SELECT
    gen_random_uuid() AS id,
    format(
      'IDF %s %s',
      (ARRAY['Atelier','Maison','Studio','Comptoir','Club','Factory','Select','District','Loft','Spot'])[1 + (random() * 9)::int],
      (ARRAY['Insolit','Nova','Pulse','Origin','Social','Prime','Week-end','Urban','Pop','Signature'])[1 + (random() * 9)::int]
    ) AS name,
    format(
      '%s %s, %s %s',
      (5 + (random() * 180)::int),
      (ARRAY['Rue de la Republique','Rue Victor Hugo','Avenue Jean Jaures','Rue Nationale','Avenue de la Gare','Rue Pasteur','Rue du General Leclerc','Rue Carnot','Rue de Paris','Boulevard Voltaire'])[1 + (random() * 9)::int],
      c.postal_code,
      c.city
    ) AS address,
    point(
      c.lng + ((random() - 0.5) * 0.06),
      c.lat + ((random() - 0.5) * 0.06)
    ) AS coordinates,
    cr.id AS category_id
  FROM generate_series(1, 55) AS gs
  JOIN LATERAL (
    SELECT city, postal_code, lat, lng
    FROM idf_cities
    ORDER BY (-LN(GREATEST(random(), 1e-9)) / weight)
    LIMIT 1
  ) c ON TRUE
  JOIN categories_ranked cr
    ON cr.rn = (((gs - 1) % cr.total) + 1)
)
INSERT INTO merchants (id, name, address, coordinates, category_id)
SELECT id, name, address, coordinates, category_id
FROM merchant_rows;

-- -------------------------------------------------
-- 2) Exactly 100 detailed promos
-- -------------------------------------------------
WITH categories_ranked AS (
  SELECT
    c.id,
    c.label,
    row_number() OVER (ORDER BY c.id) AS rn,
    COUNT(*) OVER () AS total
  FROM categories c
), merchant_pool AS (
  SELECT
    m.id,
    m.name,
    c.label AS category_label,
    cr.rn AS category_rn,
    row_number() OVER (PARTITION BY cr.rn ORDER BY random()) AS merchant_pos,
    COUNT(*) OVER (PARTITION BY cr.rn) AS merchants_in_category
  FROM merchants m
  JOIN categories_ranked cr ON cr.id = m.category_id
  JOIN categories c ON c.id = m.category_id
  WHERE m.name LIKE 'IDF %'
), promo_slots AS (
  SELECT
    gs AS idx,
    (((gs - 1) % (SELECT total FROM categories_ranked LIMIT 1)) + 1) AS target_category_rn,
    (((gs - 1) / (SELECT total FROM categories_ranked LIMIT 1)) + 1) AS category_cycle
  FROM generate_series(1, 100) AS gs
), promo_rows AS (
  SELECT
    ps.idx,
    mp.id AS merchant_id,
    mp.name AS merchant_name,
    mp.category_label
  FROM promo_slots ps
  JOIN merchant_pool mp
    ON mp.category_rn = ps.target_category_rn
   AND mp.merchant_pos = (((ps.category_cycle - 1) % mp.merchants_in_category) + 1)
)
INSERT INTO promos (title, description, promo_code, end_date, is_exclusive, merchant_id)
SELECT
  CASE translate(lower(pr.category_label), 'éèêëàâäîïôöùûüç', 'eeeeaaaiioouuuc')
    WHEN 'food' THEN format('Menu complet -%s%% chez %s', 20 + (random() * 25)::int, pr.merchant_name)
    WHEN 'sport' THEN format('Abonnement decouverte %s mois chez %s', 1 + (random() * 2)::int, pr.merchant_name)
    WHEN 'culture' THEN format('Sortie culture: 2 places pour 1 chez %s', pr.merchant_name)
    WHEN 'tech' THEN format('Accessoires high-tech a prix reduit chez %s', pr.merchant_name)
    WHEN 'mode' THEN format('Selection style -%s%% chez %s', 15 + (random() * 30)::int, pr.merchant_name)
    WHEN 'beaute' THEN format('Soin signature offert a partir de 29EUR chez %s', pr.merchant_name)
    WHEN 'chill' THEN format('Session detente duo a tarif preferentiel chez %s', pr.merchant_name)
    ELSE format('Experience locale exclusive chez %s', pr.merchant_name)
  END AS title,
  CASE translate(lower(pr.category_label), 'éèêëàâäîïôöùûüç', 'eeeeaaaiioouuuc')
    WHEN 'food' THEN
      'Offre valable sur place ou a emporter du lundi au jeudi. Inclut plat, accompagnement et boisson. Reservation conseillee en soiree.'
    WHEN 'sport' THEN
      'Acces illimite aux espaces cardio et musculation sur le creneau choisi. Une seance coaching incluse pour les nouveaux inscrits.'
    WHEN 'culture' THEN
      'Valable sur une selection d evenements et seances en semaine. Billets envoyes apres validation de la reservation.'
    WHEN 'tech' THEN
      'Remise immediate sur les references participantes en boutique. Garantie constructeur conservee et retrait en magasin possible.'
    WHEN 'mode' THEN
      'Applicable sur la nouvelle collection et une partie des essentiels. Essayage en magasin et echange sous 14 jours.'
    WHEN 'beaute' THEN
      'Diagnostic personnalise inclus, produits adaptes au type de peau et conseils d entretien a domicile en fin de seance.'
    WHEN 'chill' THEN
      'Ambiance calme, boisson incluse et acces aux espaces lounge. Offre ideale en fin de journee ou le week-end.'
    ELSE
      'Bon plan exclusif INSOLIT en Ile-de-France, quantites limitees selon disponibilite du partenaire.'
  END AS description,
  format('IDF-%s', upper(substr(md5(random()::text || pr.idx::text), 1, 8))) AS promo_code,
  (CURRENT_DATE + (10 + (random() * 120)::int))::date AS end_date,
  (random() < 0.35) AS is_exclusive,
  pr.merchant_id
FROM promo_rows pr;

COMMIT;

-- -------------------------------------------------
-- Quick checks
-- -------------------------------------------------
-- SELECT COUNT(*) AS merchants_count FROM merchants;
-- SELECT COUNT(*) AS promos_count FROM promos;
-- SELECT COUNT(*) AS promos_paris_centre
-- FROM promos p
-- JOIN merchants m ON m.id = p.merchant_id
-- WHERE m.address ~ '7500[1-6]';
-- SELECT COUNT(*) AS promos_hors_paris_75
-- FROM promos p
-- JOIN merchants m ON m.id = p.merchant_id
-- WHERE m.address !~ ' 75[0-9]{3} ';
